### ISSUE TITLE
Make this library PEP561 compatible

### ISSUE THREAD

**Issue by sobolevn** [thejohnfreeman/python-typeclasses#1]
It looks like you are not shipping `py.typed` file to end users, so all your code will be mocked as `Any`. I guess, that's not what you want.

Ref: https://www.python.org/dev/peps/pep-0561/

So, it this on scope of the project to make it type-safe for the end users?
I will send a PR with the fix.

**Comment by sobolevn** [comment]
Oh, looks like you don't have any annotations inside your code. 
My bad, I though that it is typed after finding `mypy` related tasks.

**Comment by thejohnfreeman** [comment]
I'll see what annotations I can add. I'll accept your patch regardless.
