### ISSUE TITLE
How is this different from functools.singledispatch?

### ISSUE THREAD

**Issue by alexmojaki** [thejohnfreeman/python-typeclasses#3]
This seems very similar to https://docs.python.org/3/library/functools.html#functools.singledispatch

Am I missing something?

**Comment by thejohnfreeman** [comment]
Indeed, this point has been brought up on [Twitter](https://twitter.com/psuter/status/1146432677446336513) and [Reddit](https://www.reddit.com/r/Python/comments/c8oo02/ad_hoc_polymorphism_in_python_with_type_classes/esom0uu/?context=3). The major differences are:

1. You can put the type parameter anywhere in the argument list, not just the first position.
2. You can define overloads for protocols (structural types) in addition to types.

I'll see about adding a Related Work section to the README.
